#!/usr/bin/env bash
# Clear local build output. Safe to run any time — everything here is regenerated by a build.
#
# Does NOT touch the sibling `updates` repo: it holds the appcast and each version's cached
# Sparkle signature (meta.env), which cannot be regenerated — a historical version is never
# re-signed.
set -euo pipefail

REPO="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

rm -rf "$REPO/build"
rm -rf ~/Library/Developer/Xcode/DerivedData/Catalyst-*
find ~/Library/Developer/Xcode/Archives -maxdepth 2 -name 'Catalyst *.xcarchive' -exec rm -rf {} + 2>/dev/null || true

echo "✓ Cleared build/, Catalyst DerivedData, and archived builds."
