import Foundation

/// A data model encapsulating a terminal shell command synonym mapping.
struct AliasItem: Identifiable, Hashable, Sendable {
    /// A unique identifier required for layout rendering iterations.
    let id = UUID()
    /// The mapped string literal assigned to represent the underlying system command.
    let name: String
    /// The comprehensive bash script block executed when the alias is triggered.
    let command: String
    /// An indicator noting if this entity was originally generated by the application environment.
    let isCatalystManaged: Bool
    
    /// Initializes a new alias representation context.
    ///
    /// - Parameters:
    ///   - name: The customized trigger literal.
    ///   - command: The system execution string sequence.
    ///   - isCatalystManaged: A boolean denoting whether the application claims ownership.
    init(name: String, command: String, isCatalystManaged: Bool = false) {
        self.name = name
        self.command = command
        self.isCatalystManaged = isCatalystManaged
    }
}

/// A collection of static utility structures parsing string payloads to prevent execution escaping.
struct AliasValidator {
    
    /// Establishes whether a requested naming token meets terminal execution standards.
    ///
    /// - Parameter name: The candidate string identifier.
    /// - Returns: A boolean asserting syntactic validity.
    static func isValidAliasName(_ name: String) -> Bool {
        let pattern = "^[a-zA-Z][a-zA-Z0-9_-]*$"
        return name.range(of: pattern, options: .regularExpression) != nil
    }
    
    /// Verifies the structural integrity of an incoming command block.
    ///
    /// - Parameter command: The execution payload.
    /// - Returns: A boolean asserting the command possesses non-whitespace characters.
    static func isValidCommand(_ command: String) -> Bool {
        !command.trimmingCharacters(in: .whitespaces).isEmpty
    }
    
    /// Strips unsafe terminal boundary tokens out of mapped command strings.
    ///
    /// - Parameter name: The raw command string identifier.
    /// - Returns: A functionally safe execution string representation.
    static func sanitizeName(_ name: String) -> String {
        name.replacingOccurrences(of: "[^a-zA-Z0-9_-]", with: "", options: .regularExpression)
    }
}
